# Generated by Django 5.2 on 2025-05-04 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vessel_board_boardvessel_shot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardvessel',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='api.vessel'),
        ),
        migrations.AlterField(
            model_name='shot',
            name='impact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.boardvessel'),
        ),
    ]
