# Generated by Django 5.2.1 on 2025-05-26 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_boardvessel_vessel_alter_shot_impact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='impact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.boardvessel'),
        ),
    ]
