[book]
authors = ["Xavier Baró"]
language = "en"
multilingual = false
src = "src"
title = "Software Distribuit 2024/2025"

[preprocessor.github-authors]
command = "mdbook-github-authors"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.alerts]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]